// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn28mztAvzFozCjIlCWtWrsdEpU39G2mM',
    appId: '1:846649424085:web:12ec7724336f0e0ef08a5c',
    messagingSenderId: '846649424085',
    projectId: 'food-beauty-ninja',
    authDomain: 'food-beauty-ninja.firebaseapp.com',
    databaseURL: 'https://food-beauty-ninja-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'food-beauty-ninja.appspot.com',
    measurementId: 'G-47TGZCZ2YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-4M0XLBKdZQJrlOZ_doiMcutdvQnvcEc',
    appId: '1:846649424085:android:4e5ff065816b8a52f08a5c',
    messagingSenderId: '846649424085',
    projectId: 'food-beauty-ninja',
    databaseURL: 'https://food-beauty-ninja-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'food-beauty-ninja.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpAwFs48LX-H5_893vVcgmNvHiS2FQD1A',
    appId: '1:846649424085:ios:615fc15b99a3aa14f08a5c',
    messagingSenderId: '846649424085',
    projectId: 'food-beauty-ninja',
    databaseURL: 'https://food-beauty-ninja-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'food-beauty-ninja.appspot.com',
    iosClientId: '846649424085-qja35juh3dpvcm47pr57jm9j1fujruvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );
}
